package com.example.fitnessdashboard.domain.model

enum class FitnessErrorCode {
    INVALID_REQUEST,
    MALFORMED_JSON,
    PROVIDER_UNAVAILABLE,
    GOOGLE_ACCOUNT_REQUIRED,
    PERMISSION_DENIED,
    PERMISSION_REVOKED,
    AUTHENTICATION_FAILED,
    DATA_READ_FAILED,
    UNSUPPORTED_METRIC,
    NO_DATA,
    RECORDING_SUBSCRIPTION_FAILED,
    UNKNOWN
}
